### ISSUE TITLE
AttributeError from example read_disc_information.py

### ISSUE THREAD

**Issue by Wistral** [python-scsi/python-scsi#101]
```sh
sudo `which python` read_disc_information.py /dev/sdc
```

error trace like
>Traceback (most recent call last):
  File "read_disc_information.py", line 87, in <module>
    main()
  File "read_disc_information.py", line 54, in main
    cmd = s.readdiscinformation(data_type, alloc_len=512)
  File "/home/shan/miniconda3/envs/scsi/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 518, in readdiscinformation
    opcode = self.device.opcodes.READ_DISC_INFORMATION
AttributeError: type object 'Enum' has no attribute 'READ_DISC_INFORMATION'

installed via pip

environment
```
Python 3.7.13
Linux x 5.4.0-100-generic #113~18.04.1-Ubuntu SMP Mon Feb 7 15:02:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PYSCSI-2.1.1.dev2+g4949b4b
cython-sgio-1.2.dev20+gbe246e6
```
The installation is alright, and the unit tests pass with only a warning.

The /dev/sdc of mine is acually a simple USB floppy device.
I'm a new coder, maybe I misused the example script?

**Comment by rosjat** [comment]
hi,

i would guess your code isnt getting the correct opcodes when you init the device. by default a device is initalized with spc opcodes but for this you need the mmc opcodes. 

take a look here [scsi_enum_command.py](https://github.com/python-scsi/python-scsi/blob/master/pyscsi/pyscsi/scsi_enum_command.py) 

so you should check if the usb device is recognized as multimedia device by the code  in _init_opcode methode in [scsi.py](https://github.com/python-scsi/python-scsi/blob/master/pyscsi/pyscsi/scsi.py)

**Comment by Wistral** [comment]
```py
            self.device.devicetype = self.inquiry().result['peripheral_device_type']
            print(f'device type: {self.device.devicetype}')
            # got type output: 0
            if self.device.devicetype in (0x00, 0x04, 0x07, ):  # sbc
                self.device.opcodes = sbc
            ...
            elif self.device.devicetype in (0x05,):  # mmc
                self.device.opcodes = mmc
```
the type should be mmc, but it got to be 0x00.
`self.inquiry().result['peripheral_device_type']` gave the incorrect info.

After adding debug codes, `self.inquiry().result` output as follows:
>inquiry return {'peripheral_qualifier': 0, 'peripheral_device_type': 0, 'rmb': 1, 'version': 6, 'normaca': 0, 'hisup': 1, 'response_data_format': 2, 'additional_length': 67, 'sccs': 0, 'acc': 0, 'tpgs': 0, '3pc': 0, 'protect': 0, 'encserv': 0, 'vs': 0, 'multip': 0, 'addr16': 0, 'wbus16': 0, 'sync': 0, 'cmdque': 0, 'vs2': 0, 't10_vendor_identification': bytearray(b'SanDisk\x00'), 'product_identification': bytearray(b'Ultra Fit\x00\x00\x00\x00\x00\x00\x00'), 'product_revision_level': bytearray(b'1.00'), 'clocking': 0, 'qas': 0, 'ius': 0}
device type: 0



if I force devicetype set to 0x05, output still seems strange
>device type: 5
DISC_INFORMATION_DATA_TYPE: STANDARD_DISC_INFORMATION (0)
ERASABLE: 0
STATE_OF_LAST_SESSION: EMPTY_SESSION (0)
DISC_STATUS: EMPTY_DISC (0)
NUMBER_OF_FIRST_TRACK_ON_DISC: 0
NUMBER_OF_SESSIONS: 0
FIRST_TRACK_NUMBER_IN_LAST_SESSION: 0
LAST_TRACK_NUMBER_IN_LAST_SESSION: 0
DID_V: 0
DBC_V: 0
URU: 0
DAC_V: 0
LEGACY: 0
BG_FORMAT_STATUS: 0
DISC_TYPE: CD-DA or CD-ROM (0)
DISC_IDENTIFICATION: 0
LAST_SESSION_LEAD_IN_START_ADDRESS bytearray(b'\x00\x00\x00\x00')
LAST_POSSIBLE_LEAD_OUT_START_ADDRESS bytearray(b'\x00\x00\x00\x00')
DISC_BAR_CODE bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00')

**Comment by rosjat** [comment]
well if you take a look at the inquiry you see the device is a san disk ultra fit, i dont think thats a multi media device. if its a simply usb stick it should identify as a block device and it does.

**Comment by Wistral** [comment]
OK, got it, thanks. 
I just try another CD-ROM device, output as follow.
>$ sudo `which python` read_disc_information.py /dev/sr0
SCSIDevice.__init__(device=/dev/sr0,readwrite=False,detect_replugged=True)
SCSI object __init__(self,dev=SCSIDevice,blocksize=0)
call inquiry(self,evpd=0,page_code=0,alloclen=96):
inquiry return {'peripheral_qualifier': 0, 'peripheral_device_type': 5, 'rmb': 1, 'version': 0, 'normaca': 1, 'hisup': 1, 'response_data_format': 2, 'additional_length': 91, 'sccs': 0, 'acc': 0, 'tpgs': 0, '3pc': 0, 'protect': 0, 'encserv': 0, 'vs': 0, 'multip': 0, 'addr16': 0, 'wbus16': 0, 'sync': 0, 'cmdque': 0, 'vs2': 0, 't10_vendor_identification': bytearray(b'TSSTcorp'), 'product_identification': bytearray(b'DVD+-RW SU-208GB'), 'product_revision_level': bytearray(b'H100'), 'clocking': 0, 'qas': 0, 'ius': 0}
device type: 5
DISC_INFORMATION_DATA_TYPE: STANDARD_DISC_INFORMATION (0)
ERASABLE: 0
STATE_OF_LAST_SESSION: COMPLETE_SESSION (3)
DISC_STATUS: FINALIZED_DISC (2)
NUMBER_OF_FIRST_TRACK_ON_DISC: 1
NUMBER_OF_SESSIONS: 1
FIRST_TRACK_NUMBER_IN_LAST_SESSION: 1
LAST_TRACK_NUMBER_IN_LAST_SESSION: 1
DID_V: 0
DBC_V: 0
URU: 1
DAC_V: 0
LEGACY: 0
BG_FORMAT_STATUS: 0
DISC_TYPE: CD-DA or CD-ROM (0)
DISC_IDENTIFICATION: 0
LAST_SESSION_LEAD_IN_START_ADDRESS bytearray(b'\x00\x00\x00\x00')
LAST_POSSIBLE_LEAD_OUT_START_ADDRESS bytearray(b'\x00\x00\x00\x00')
DISC_BAR_CODE bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00')

Did that seem to work properly?

**Comment by rosjat** [comment]
Since we wrote code for SG_IO this is a lib for generic scsi  devices this includes block devices of course. We only implement a subset of CDBs but most commands in the lib are supported by most device types. take a look at the scsi_enum_command.py there you  can find most opcodes for the specific device types and then you simply need to check the scsi_cdb_* files to find supported commands. For general research you can go to t10.org.

**Comment by Wistral** [comment]
Thank you very much! the provided info is really helpful.
