### ISSUE TITLE
run tools/swp.py show "AttributeError" error

### ISSUE THREAD

**Issue by jackeichen** [python-scsi/python-scsi#102]
After run tools/swp.py: 
      python3 swp.py --on /dev/sda

An "AttributeError" error occurs， below is the details：

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyscsi/pyscsi/scsi_command.py", line 258, in unmarshall
    self.result = self.unmarshall_datain(self.datain, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyscsi/pyscsi/scsi_cdb_modesense6.py", line 221, in unmarshall_datain
    return ModeSense6.unmarshall_dataout(data)
AttributeError: type object 'ModeSense6' has no attribute 'unmarshall_dataout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "swp.py", line 66, in <module>
    main()
  File "swp.py", line 58, in main
    s.modeselect6(i)
  File "/usr/local/lib/python3.6/site-packages/pyscsi/pyscsi/scsi.py", line 248, in modeselect6
    cmd.unmarshall()
  File "/usr/local/lib/python3.6/site-packages/pyscsi/pyscsi/scsi_command.py", line 260, in unmarshall
    raise NotImplementedError('%s has no method to unmarshall datain data' % self)
NotImplementedError: ModeSelect6 has no method to unmarshall datain data

**Comment by rosjat** [comment]
hi jack,

do you run the code on a block device? can you give short review what you did or post the code you used? I will try to have a look at the swp code as soon as possible 

cheers 

Markus

**Comment by rosjat** [comment]
Also beaware you shouldnt simply copy and paste our code and use it in your project, if you wannt to use our work you should use it in the way intended and use our package to handle scsi commands.

thanks

**Comment by sahlberg** [comment]
@rojsat   I have sent a PR to fix this. We should not attempt to unmarshall as modeselect6/10 do not return any data.

@jackeichen please do not fork this code.  There are so very very few people working on the scsi commandset as it is that we should not risk that we fracture the tiny tine developer base that exist and start having diverging codebases. Everyone will lose in that scenario.   Could you instead either pull in python-scsi as a ependency or maybe just as a git submodule instead?
Just so that we don't risk spreading the tiny developer base even thinner.

regards

**Comment by jackeichen** [comment]
@rosjat @sahlberg  Thanks for the contribution in this project(it's really awesome), and the prompt reply in this issue.

I totally undershand your worry, I will use it as a dependency  instead of copying code from python-scsi in my project. But before that could i open an new issue to request a passthrough16/passthrough12 command? It will be easy for me to do the next work, if the request is not to be considered, i will have to re-make a new methmod in the base of current python-scsi code to realize this function. Actually I didn‘t change the python-scsi code until i try to use it to send ATA command set. I ever considered using it as a dependency to prevent me ceaselessly merging with the source code, before I found that it is more easy to change in your code. I will finish this work in future, anyway .

thanks

**Comment by rosjat** [comment]
@jackeichen as I stated before you are more then welcome to contribute a new command to the project if you got code already.

**Comment by sahlberg** [comment]
>But before that could i open an new issue to request a passthrough16/passthrough12 command? 

Do you have a link to the documents where these commands are finalized?
Shouldn't be too terrible to add.  I can give it a try this weekend but I will need you to do testing on it,

**Comment by jackeichen** [comment]
I test the new code, I think the "AttributeError" issue is fixed!
