### ISSUE TITLE
Request for new command ATA PASS-THROUGH command for use

### ISSUE THREAD

**Issue by jackeichen** [python-scsi/python-scsi#106]
I want to use the code to send ATA command to storage device, but it doesn’t support ATA PASS-THROUGH command now.
So could you add the support for this commands in this project?

Here is what i want:
Command name                    Operation code
ATA PASS-THROUGH (12)      A1h
ATA PASS-THROUGH (16)      85h

And the releated spec can be download from: https://www.t10.org/cgi-bin/ac.pl?t=f&f=sat5r08.pdf ， and i think the most import content is in chapter 12 " SATL specific command set extensions".

**Comment by rosjat** [comment]
i will take a look at it but dont expect it to work tomorrow since i need to read up on it to begin with

**Comment by jackeichen** [comment]
@rosjat  I‘m working on it too, but i'm more familiar with ATA/NVMe command set, not the scsi command set. So please help to review the code and coding style before merge it, this may help you to speed up this work.

I think the code can be finished in this weekend, code will be tested in two different vendor SATA disks(a HDD and a ssd). PATA Device is not considered as it is such an old type.

**Comment by rosjat** [comment]
@jackeichen  as i said before you are more then welcome to contribute code so if you got some already we can review
