### ISSUE TITLE
If potential memory issue, when send a lot of io commands in a short period?

### ISSUE THREAD

**Issue by jackeichen** [python-scsi/python-scsi#122]
Let's say we have a situation: send a lot of io commands in a short period of time, in a small memory capacity system.

The code in scsi_command will create datain or dataout in every command we create, and sometimes the GC in python is not so efficient. This may lead to a shortage of memory.

**Comment by rosjat** [comment]
in general this should be fairly easy to do since we could pass the byte array into the __init__ method only thing we need to check first how it effects the existing code.  it is reasonable to reuse allocated memory for situations like you pointed out.

**Comment by jackeichen** [comment]
> in general this should be fairly easy to do since we could pass the byte array into the **init** method only thing we need to check first how it effects the existing code. it is reasonable to reuse allocated memory for situations like you pointed out.

Yes, it is a corner case. I got this by running a program containing infinite loop (Oh, it's my fault), and then the OS become slower and slower. 

So i think it's more reasonable to handle this situation: a lot of IO commands in a short period of time, or even a Syntax Error.

I understand what you post in the reply, what if add two kwargs: datain_ba=None & dataout_ba=None, and set a lower priority than dataout_alloclen and datain_alloclen in class SCSICommand.

**Comment by rosjat** [comment]
Adding args isn't a solution in general, if we refactor stuff we should do it in a way that benefits the code in the long run. I will look at the code and I am sure we will find a solution that doesn't cause to much work for people who have existing code

**Comment by jackeichen** [comment]
Got it. But I hope to retain what we have now: 
1. It becomes easy to familiarize and do development with the code in the early days, without initialize the memory by user;
2. In most of the time and case, we do not need initialize the memory ourself.

Thank you for the reply, and further works for this issue!

**Comment by rosjat** [comment]
yeah as i said, i take a look and if we can live without changing things we'll do.

**Comment by jackeichen** [comment]
More test is done.

This case only arised from delayed command object delete. For example:
```
result = []
with SCSI(device, blocksize=512) as s:
    while (i < max_sctors)
            r = s.read16(
                  i,
                  256,
            )
            i += 256
            result.append(r)
## handle result here
pass
```
This can be avoid by the user's handle methmod, and the gc is enough for this case.
```
with SCSI(device, blocksize=512) as s:
    while (i < max_sctors)
            r = s.read16(
                  i,
                  256,
            )
            i += 256
            ## handle each result here
            pass
```

Let me know if I can close this issue?

**Comment by rosjat** [comment]
Well if you found a solution for your code that doesn't really concern this library we close this
