### ISSUE TITLE
strange errors with 'tgt' target

### ISSUE THREAD

**Issue by folkertvanheusden** [python-scsi/python-scsi#133]
Hi,

I've installed python-scsi from git. Trying a simple program fails mysteriously with the 'tgt' target.

Installation:

```
Defaulting to user installation because normal site-packages is not writeable
Processing /home/folkert/Projects/python-scsi
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: PYSCSI
  Building wheel for PYSCSI (pyproject.toml) ... done
  Created wheel for PYSCSI: filename=PYSCSI-2.1.1.dev37+geab5ee7-py3-none-any.whl size=116412 sha256=b9d2ee00b10f28a41e85c6a8f99d6539c4aa59bbc473f8c607b1903018451dde
  Stored in directory: /home/folkert/.cache/pip/wheels/53/38/73/fbfc66c67471da1b5a7c6543d398770bc94602bd7b63111b10
Successfully built PYSCSI
Installing collected packages: PYSCSI
  Attempting uninstall: PYSCSI
    Found existing installation: PYSCSI 2.1.0
    Uninstalling PYSCSI-2.1.0:
      Successfully uninstalled PYSCSI-2.1.0
Successfully installed PYSCSI-2.1.1.dev37+geab5ee7
```

strange error:

```
$ ../test-io.py 
Step: 3
  write
Traceback (most recent call last):
  File "/home/folkert/Projects/python-scsi/../test-io.py", line 20, in <module>
    w = s.write16(i, step, data).dataout
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyscsi/scsi.py", line 640, in write16
    opcode = self.device.opcodes.WRITE_16
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Enum' has no attribute 'WRITE_16'
```

simple test-program that I try to use:

```python
#! /usr/bin/python3

# https://github.com/python-scsi/python-scsi/

from pyscsi.pyscsi.scsi import SCSI
from pyscsi.utils import init_device

device = init_device('iscsi://192.168.65.245/test2/0')
bs = 4096
count = 256
step_start = 3

with SCSI(device, blocksize=bs) as s:
    for step in range(step_start, count):
        print(f'Step: {step}')
        print('  write')
        for i in range(0, count, step):
            data = bytearray([ i ] * bs)
            w = s.write16(i, step, data).dataout

        print('  read & verify')
        for i in range(0, count, step):
            r = s.read16(i, step).datain

            for t in range(0, count):
                if r[t] != i:
                    print(r[t], i, r[t] == i)
```

Note that this (the python-script) works perfectly fine when it talks to my toy-iscsi-target which makes it even stranger.

Network trace:
[problem-pcap.zip](https://github.com/python-scsi/python-scsi/files/14122202/problem-pcap.zip)

**Comment by rosjat** [comment]
this can be caused by the device initialization where you might get the wrong opcodes. By default you will be set to spc and spc has no write_16. try to provide the opcode you desire when you init the device for block devices sbc is the opcode Enum you want.

**Comment by folkertvanheusden** [comment]
No luck sofar:

```
$ python3 read16_with_contextmanger.py iscsi://192.168.65.245/test/0
we run with init_device helper
Traceback (most recent call last):
  File "/home/folkert/Projects/iesp/python-scsi/examples/read16_with_contextmanger.py", line 72, in <module>
    with_init_device(init_device(sys.argv[1]))
  File "/home/folkert/Projects/iesp/python-scsi/examples/read16_with_contextmanger.py", line 35, in with_init_device
    d.execute(cmd)
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyiscsi/iscsi_device.py", line 107, in execute
    raise self.CheckCondition(cmd.sense)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyscsi/scsi_sense.py", line 941, in __init__
    self.valid = sense[0] & 0x80
                 ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

nor with

```python
$ cat test.py 
#! /usr/bin/python3

from pyscsi.pyscsi.scsi_cdb_write16 import Write16
from pyscsi.pyscsi.scsi_enum_command import sbc
from pyscsi.pyscsi.scsi import SCSI
from pyscsi.utils import init_device

device = init_device('iscsi://192.168.65.245/test/0')
bs = 4096
with SCSI(device, blocksize=bs) as d:
    d.execute(Write16(sbc.WRITE_16, blocksize=bs, lba=0, tl=1, data=bytearray([ 1 ] * bs)))
```

```
$ ./test.py 
Traceback (most recent call last):
  File "/home/folkert/Projects/iesp/python-scsi/examples/./test.py", line 11, in <module>
    d.execute(Write16(sbc.WRITE_16, blocksize=bs, lba=0, tl=1, data=bytearray([ 1 ] * bs)))
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyscsi/scsi.py", line 107, in execute
    raise e
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyscsi/scsi.py", line 105, in execute
    self.device.execute(cmd)
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyiscsi/iscsi_device.py", line 107, in execute
    raise self.CheckCondition(cmd.sense)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyscsi/scsi_sense.py", line 941, in __init__
    self.valid = sense[0] & 0x80
                 ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rosjat** [comment]
again 

`device = init_device('iscsi://192.168.65.245/test/0')`

this seems to set spc as opcode, so 

```
with SCSI(device, blocksize=bs) as d:
    d.execute(Write16(sbc.WRITE_16, blocksize=bs, lba=0, tl=1, data=bytearray([ 1 ] * bs)))
```

has still spc as opcode. To over come this without using SCSICommand in the way I pointed out you could try to  simply 

`d.device.opcodes = sbc`

and then the correct opcode enum should be accessable by scsi object

**Comment by folkertvanheusden** [comment]
Hi,
Thanks but even with that I get the 

```
  File "/home/folkert/.local/lib/python3.11/site-packages/pyscsi/pyscsi/scsi_sense.py", line 941, in __init__
    self.valid = sense[0] & 0x80
                 ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

error. This is different from the situation where I do not set the enum.
I think the problem is that no sense data is returned while the code expects it to be.

**Comment by rosjat** [comment]
sorry was to slow as I stated in the edited post cmd.sense seems to be the problem here if there is nothing in the sense data of the command then nothing can be accessed maybe try to set the en_raw_sense attribute to  True on the execute command and see if you get some sense data

**Comment by rosjat** [comment]
```python
        if task.status == scsi_enum_command.SCSI_STATUS.CHECK_CONDITION:
            # Match recent addition to SCSIDevice
            if en_raw_sense:
                cmd.raw_sense_data = cmd.sense
            # No sense information propagated.
            raise self.CheckCondition(cmd.sense)
```
If you expect sense data from your command because you got Check_Condition
you will hit this raise but with `en_raw_sense=True` you should get some sense data that will passed to CheckCondition

**Comment by rosjat** [comment]
the target should give you sense data if it tells you check condition, if it doesnt give sense data then the code can't try to make sense of it anyway

**Comment by folkertvanheusden** [comment]
Tried that but same error

```python
d.execute(Write16(sbc.WRITE_16, blocksize=bs, lba=0, tl=1, data=bytearray([ 1 ] * bs)), en_raw_sense=True)
```

Unfortunately 'tgt' gives hardly any usable logging.

I looked at the networktrace and verified that it supports SBC-3:

![image](https://github.com/python-scsi/python-scsi/assets/85709915/3e7059c9-6318-463c-b960-0175f61238f2)

but:

![image](https://github.com/python-scsi/python-scsi/assets/85709915/03cb05b2-9991-4811-ab35-d04b29a9aa8e)

So a command is send which is not understood.

![image](https://github.com/python-scsi/python-scsi/assets/85709915/66d92b19-73d5-4203-a947-21b57132e1a1)

8a is WRITE_16, as expected.

And then it hit me: I was talking to lun 0, but that's the controller. I changed it to lun 1 (verified with `tgtadm --mode target --op show`) and...working!

So the problem was all mine. Thanks a lot for your patience and help!

**Comment by rosjat** [comment]
ok I wrote @sahlberg  a mail to try to find pointers to the tgt stuff since he is the authority on iscsi anyway ;)

**Comment by rosjat** [comment]
> And then it hit me: I was talking to lun 0, but that's the controller. I changed it to lun 1 (verified with `tgtadm --mode target --op show`) and...working!
> 
> So the problem was all mine. Thanks a lot for your patience and help!

ok yeah the controller might not give you a sense ther ;)
