### ISSUE TITLE
pypi package

### ISSUE THREAD

**Issue by rosjat** [python-scsi/python-scsi#84]
so we had some kind of pypi package that didnt took care of dependecies at all, with the move to cython-sgio and cython-iscsi this might be a good point to revisit this. I need to take a look at this since i didnt really spend time with this back then but maybe we can work it out sooner or later

**Comment by Flameeyes** [comment]
Do you want to make a release, maybe after #95? I think we're in a good place for 2.0.0. If that's the case, the following commands should take care of the whole thing:

```
(venv) $ git clean -fxd  # CAREFUL — deletes any file not tracked by git!
(venv) $ pip install -e .[dev]
(venv) $ git tag -a PYSCSI-2.0.0
(venv) $ python setup.py --version  # just to confirm it reports 2.0.0
(venv) $ python setup.py sdist bdist_wheel
(venv) $ twine upload dist/*
```

**Comment by rosjat** [comment]
will take a look at it next week but i guess if noting breaks we can do that

**Comment by rosjat** [comment]
thanks diego for fixing this :)

will close tis now
