### ISSUE TITLE
Cannot install pyscsi via pip 

### ISSUE THREAD

**Issue by gsegria** [python-scsi/python-scsi#98]
I cannot install pyscsi via pip success.
Any one know why?

root@test:/home/test/my/python-scsi# pip install pyscsi
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting pyscsi
  Using cached PYSCSI-1.0.tar.gz (42 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-aw493exj/pyscsi_f7c3d231d88642d8a5d8da50bef2680a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-aw493exj/pyscsi_f7c3d231d88642d8a5d8da50bef2680a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kgeex338
         cwd: /tmp/pip-install-aw493exj/pyscsi_f7c3d231d88642d8a5d8da50bef2680a/
    Complete output (15 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-kgeex338/PYSCSI.egg-info
    writing /tmp/pip-pip-egg-info-kgeex338/PYSCSI.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-kgeex338/PYSCSI.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-kgeex338/PYSCSI.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-kgeex338/PYSCSI.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-kgeex338/PYSCSI.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-kgeex338/PYSCSI.egg-info/SOURCES.txt'
    running egg_info
    creating /tmp/pip-pip-egg-info-kgeex338/LINUX_SGIO.egg-info
    writing /tmp/pip-pip-egg-info-kgeex338/LINUX_SGIO.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-kgeex338/LINUX_SGIO.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-kgeex338/LINUX_SGIO.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-kgeex338/LINUX_SGIO.egg-info/SOURCES.txt'
    error: package directory 'linux_sgio' does not exist
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/19/5da8e1a53396fa2631024643d70cced149ba738bb9740d259cb4a251c437/PYSCSI-1.0.tar.gz#sha256=b8cfb5be04c68a66c5e8e1c38b0d9538e55eca4a897895f2f54cdc6752d7e152 (from https://pypi.org/simple/pyscsi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyscsi (from versions: 1.0)
ERROR: No matching distribution found for pyscsi
WARNING: You are using pip version 21.2.4; however, version 21.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

**Comment by rosjat** [comment]
I guess you downloaded the tar.gz over the latest release link right. Don't use this release it wont work with the cython packages! Clone the sorce from the master branch and follow the build/install instructions in the readme.md.

**Comment by rosjat** [comment]
Are you able to install the latest version ?

**Comment by RVP04** [comment]
It says 
zsh: no matches found: .[iscsi,sgio]

Can you please help me.

**Comment by rosjat** [comment]
are you installing the latest version 2.0.1 ?

[pypi](https://pypi.org/project/PYSCSI/)

**Comment by RVP04** [comment]
@rosjat i am trying to run this package for that support of this package is required. 
https://github.com/kasbert/JQ6500-tool

And now i am getting error in the import statement.

**Comment by rosjat** [comment]
well pyscsi has dependencies on its own, namely [cython-sgio](https://github.com/python-scsi/cython-sgio) and if you want to use iscsi [cython-iscsi](https://github.com/python-scsi/cython-iscsi) so if you dont use pip for the install you need to make sure one of those packages are installed too. I guess you only need cython-sgio
